server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt
    username: jwt
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: samscott0168@gmail.com
    password: pxasaqxjbuvhjljh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000